# -*- coding: utf-8 -*-
"""P1LAB1_NguyenBryan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZP1QnKNjoW7sGybY-3anVgh2uhn5PYR_
"""



#Bryan Nguyen
#02/05/2025
#P1LAB1
#Using input and print functions

#Get info from user
f_name = input("Please enter your first name: ")
l_name = input("Please enter your last name: ")


#Display greeting to user
print("Hello,", f_name, l_name + "!", "Welcome to CTI 110!")